uploading database research doc
Gopher-Industries/Company-Docs pull request #3
Opened 2023-08-31 03:51 UTC by SamrajMahadev

This is the research documents on different types of database, different database pros and cons, comparison on various  database platform. The reason for deciding why the team choose to use MySQL database platform.

2023-09-07 03:31 UTC, deasta requested changes

2023-09-07 03:31 UTC, deasta commented on foodremedy-api/database-research.md
Consider changing filename to specify what you are researching such as 'Relational vs. Non-Relational database research.md'

2023-09-07 03:31 UTC, deasta commented on foodremedy-api/database-research.md
also quickly add an introduction explaining what this document is.

2023-09-07 04:05 UTC, SamrajMahadev commented on foodremedy-api/database-research.md
thank you for reviewing, i'll make the changes and updated the files..

2023-09-12 02:18 UTC, abinabra commented on foodremedy-api/database-research.md
The changes look good and the introduction and the conclusion looks good. I will resolve this now.

2023-09-12 02:28 UTC, merged